server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/reactive_spring_rest_jwt

app:
  jwt:
    hmac:
      secret-key: LKsdjflkhsd2834fsdlfjLADKS@#*GHSDKDFJ20FJASDLKF
