server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:37017/reactive_spring_rest_jwt
      auto-index-creation: true

app:
  jwt:
    hmac:
      secret-key: LKsdjflkhsd2834fsdlfjLADKS@#*GHSDKDFJ20FJASDLKF
